### ISSUE TITLE
Cewe2pdf worked fine untill 5 dec 2020

### ISSUE THREAD

**Issue by robvancooten** [stfnk/Cewe2pdf#2]
Cewe2pdf worked fine untill 5 dec 2020. 
4 dec. it worked still good on Windows.  
Now suddenly I get an error:

Error:
  An assembly specified in the application dependencies manifest (Cewe2pdf.deps.json) was not found:
    package: 'Microsoft.Win32.SystemEvents', version: '4.7.0'
    path: 'runtimes/win/lib/netcoreapp3.0/Microsoft.Win32.SystemEvents.dll'
Any idea what it can be.

**Comment by stfnk** [comment]
Hi! Not really sure why this error suddenly appears.

Are you running the latest [Cewe2pdf version 0.2.0](https://github.com/stfnk/Cewe2pdf/releases/tag/v0.2.0)? This *should* be a self contained `.exe` without any dependencies and just work.

If you get the error with the current release, try this build instead:
[Cewe2pdfDeps.zip](https://github.com/stfnk/Cewe2pdf/files/5648159/Cewe2pdfDeps.zip)
It includes the missing lib mentioned in the error message. 

Hope this works for you and thanks for the report!

**Comment by robvancooten** [comment]
Your version with missing library included works indeed.I error: I think you compiled it with set the maximum of pages to 4….For the rest all well. Greetings rob   Please attach this file to bug reports. [Message] Loading '2019_De_bende_van_3.mcf'...[Warning] Unhandled Node in <fotobook> 'project'.[Warning] Unhandled Node in <fotobook> 'savingVersion'.[Warning] Unhandled Node in <fotobook> 'articleConfig'.[Warning] Unhandled Node in <fotobook> 'extra'.[Warning] Unhandled Node in <fotobook> 'userfeedback'.[Warning] Unhandled Node in <fotobook> 'fotoRelationships'.[Info]    Loading fonts from C:\Windows\Fonts[Info]    Found 1423 fonts.[Message] Starting conversion. This may take several minutes.[Message] [0,0%]       processing Page 1/4[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled area type in <page/area> 'spinelogoarea'.[Warning] Unhandled html/body/style property: ''.[Warning] Unhandled html/body/style property: ''.[Warning] Unhandled html/body/style property: ''.[Warning] Unhandled html/body/style property: ''.[Warning] Unhandled area type in <page/area> 'spinetextarea'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Message]  ...done, 0,756 seconds.[Message] [25,0%]    processing Page 2/4[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Message]  ...done, 0,314 seconds.[Message] [50,0%]    processing Page 3/4[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Message]  ...done, 0,313 seconds.[Message] [75,0%]    processing Page 4/4[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Warning] Unhandled Node in <page> 'background'.[Message]  ...done, 0,370 seconds.[Message] Saving '2019_De_bende_van_3.pdf'.[Message] Finished in 2,249 seconds.[Info]    Writing log file. From: StefanSent: zondag 6 december 2020 03:00To: stfnk/Cewe2pdfCc: robvancooten; AuthorSubject: Re: [stfnk/Cewe2pdf] Cewe2pdf worked fine untill 5 dec 2020 (#2) Hi! Not really sure why this error suddenly appears.Are you running the latest Cewe2pdf version 0.2.0? This should be a self contained .exe without any dependencies and just work.If you get the error with the current release, try this build instead:Cewe2pdfDeps.zipIt includes the missing lib mentioned in the error message.Hope this works for you and thanks for the report!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by stfnk** [comment]
Oh you're right, i did not test the build from last night... Just comitted a fix and rebuild without the 4 pages limit:
[Cewe2pdfDeps-noLimit.zip](https://github.com/stfnk/Cewe2pdf/files/5648703/Cewe2pdfDeps-noLimit.zip)
If everything works, i will also update the release version with this build.

Glad that it works for you :)

**Comment by robvancooten** [comment]
Thanks it works perfect now. 

Met vriendelijke groeten,
Rob van Cooten. 👀

**Comment by stfnk** [comment]
Great that it's working again, closing this issue then.
Thanks for reporting! 😄
